name: jennai-root
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - cudatoolkit=11.8
  - cudnn=8.9.7
  - flask
  - flask-cors
  - flask-assets
  - inquirerpy # For interactive admin scripts
  - libsass
  - numpy
  - pandas
  - requests
  - matplotlib
  - jupyter
  - pip
  - pip:
      - -r requirements.txt