# Conda environment for the VividAI project.
#
# This file uses a simplified approach: Conda manages the core Python environment,
# the CUDA toolkit, and the Redis server. Pip manages all Python package
# dependencies via the requirements.txt file. This is a robust and reliable pattern.
#
# --- How to use ---
# 1. Ensure requirements.txt exists in the same directory.
# 2. conda clean --all
# 3. conda env remove --name vivid-ai  (To ensure a clean start)
# 4. conda env create -f environment.yaml
# 5. conda activate vivid-ai

name: vivid-ai

channels:
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - redis # The Redis server itself, for local development
  - pip:
    - -r requirements.txt
