name: jennai-root
channels:
  - pytorch # Keep pytorch channel even if installing via pip, for other related dependencies
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.9 # Or your specific Python version
  # Essential CUDA toolkit and cuDNN for the environment
  - cudatoolkit=11.8
  - cudnn=8.9.7
  # Web framework and related
  - flask
  - flask-cors
  # Data handling and scientific computing
  - numpy
  - pandas
  - requests # For HTTP requests
  - matplotlib # For plotting
  # Add other conda-installable dependencies like onnxruntime-gpu, scikit-image, cupy if needed

  - pip
  - pip:
    # Pip dependencies are managed in the requirements.txt file.
    # This creates a single source of truth for Python packages.
    # Note: PyTorch with CUDA support must be installed manually.
    # See the instructions in requirements.txt for details.
    - -r requirements.txt
